export const SET_IS_FETCHING_DATA = 'airQuality/SET_IS_FETCHING_DATA';
export type SET_IS_FETCHING_DATA = typeof SET_IS_FETCHING_DATA;

export const FETCH_LATEST_DATA = 'airQuality/FETCH_LATEST_DATA';
export type FETCH_LATEST_DATA = typeof FETCH_LATEST_DATA;

export const FETCH_LATEST_DATA_SUCCESS = 'airQuality/FETCH_LATEST_DATA_SUCCESS';
export type FETCH_LATEST_DATA_SUCCESS = typeof FETCH_LATEST_DATA_SUCCESS;

export const FETCH_LATEST_DATA_FAILURE = 'airQuality/FETCH_LATEST_DATA_FAILURE';
export type FETCH_LATEST_DATA_FAILURE = typeof FETCH_LATEST_DATA_FAILURE;

export const FETCH_LATEST_DATA_PAGE = 'airQuality/FETCH_LATEST_DATA_PAGE';
export type FETCH_LATEST_DATA_PAGE = typeof FETCH_LATEST_DATA_PAGE;

export const FETCH_LATEST_DATA_PAGE_SUCCESS =
  'airQuality/FETCH_LATEST_DATA_PAGE_SUCCESS';
export type FETCH_LATEST_DATA_PAGE_SUCCESS = typeof FETCH_LATEST_DATA_PAGE_SUCCESS;

export const FETCH_LATEST_DATA_PAGE_FAILURE =
  'airQuality/FETCH_LATEST_DATA_PAGE_FAILURE';
export type FETCH_LATEST_DATA_PAGE_FAILURE = typeof FETCH_LATEST_DATA_PAGE_FAILURE;

export const SET_WORLD_AIR_QUALITY_MAP_PARAMETER_FILTER =
  'airQuality/SET_WORLD_AIR_QUALITY_MAP_PARAMETER_FILTER';
export type SET_WORLD_AIR_QUALITY_MAP_PARAMETER_FILTER = typeof SET_WORLD_AIR_QUALITY_MAP_PARAMETER_FILTER;
